local SolarisLib = loadstring(game:HttpGet("https://raw.githubusercontent.com/choy0on/Solaris/main/Source.lua"))()

local plr = game.Players.LocalPlayer
local char = plr.Character or plr.CharacterAdded:Wait()
local hum = char:WaitForChild("Humanoid")

local window = SolarisLib:New({
    Name = "Titanium",
    FolderToSave = "Titanium_Settings"
})

local mainTab = window:Tab("Main")

local MainS = mainTab:Section("Main")

MainS:Toggle("Auto Farm", false, "Farm", function(t)
    if t then
        getgenv().AutoFarm = true

        local point = workspace:FindFirstChild("Stone"):FindFirstChild("Point")

        if point ~= nil then
            char:MoveTo(Vector3.new(61, 3, -10))

            task.wait(0.1)

            keyclick(0x31)
        end

        

        while getgenv().AutoFarm do
            task.wait()
            pcall(function()
            end)
        end
    else
        getgenv().AutoFarm = false
    end
end)

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Message
local Callback = getcallbackvalue(Event, "OnClientInvoke")
Event.OnClientInvoke = function(...)
	local Args = table.pack(...)

	local Result = table.pack(
		Callback(table.unpack(Args, 1, Args.n))
	)

	return table.unpack(Result, 1, Result.n)
end

-- This code was generated by Cobalt
-- https://github.com/notpoiu/cobalt

local Event = game:GetService("ReplicatedStorage").Message
local Callback = getcallbackvalue(Event, "OnClientInvoke")
Event.OnClientInvoke = function(...)
	local Args = table.pack(...)

	local Result = table.pack(
		Callback(table.unpack(Args, 1, Args.n))
	)

	return table.unpack(Result, 1, Result.n)
end

local mtHook; mtHook = hookmetamethod(game, "__newindex", function(...)
	local self, key, value = ...
	
	if (
		rawequal(self, Event) and
		rawequal(key, "OnClientInvoke") and
		typeof(value) == "function" and
		not checkcaller()
	) then
		Callback = value
	end

	return mtHook(...)
end)

